export interface ProdutoCatalogoSeed {
  id_original: number
  nome: string
  tamanho: string
  preco_padrao: number
  categoria: string
  dica_cuidado: string
}

export const catalogoData: ProdutoCatalogoSeed[] = [
  // --- DIVERSOS / FOLHAGENS / ORQUÍDEAS ---
  { id_original: 1,   nome: "Girassol",                   tamanho: "P15",           preco_padrao: 56.90,  categoria: "Vaso",     dica_cuidado: "Sol pleno direto. Muita água." },
  { id_original: 2,   nome: "Gloxínea",                   tamanho: "P11",           preco_padrao: 24.90,  categoria: "Flor",     dica_cuidado: "Muita claridade mas sem sol direto. Não molhe as folhas." },
  { id_original: 3,   nome: "Gloxínea",                   tamanho: "P15",           preco_padrao: 53.90,  categoria: "Flor",     dica_cuidado: "Evite correntes de ar frias." },
  { id_original: 4,   nome: "Hortênsia",                  tamanho: "P15",           preco_padrao: 78.90,  categoria: "Vaso",     dica_cuidado: "Mantenha o solo sempre úmido e em local fresco." },
  { id_original: 5,   nome: "Lírio Amarelo",              tamanho: "P15",           preco_padrao: 84.90,  categoria: "Vaso",     dica_cuidado: "Corte as anteras (parte com pólen) para a flor durar mais." },
  { id_original: 6,   nome: "Lírio Branco",               tamanho: "P15",           preco_padrao: 84.90,  categoria: "Vaso",     dica_cuidado: "Perfume intenso, mantenha em local ventilado." },
  { id_original: 7,   nome: "Lírio da Paz",               tamanho: "P11",           preco_padrao: 26.90,  categoria: "Folhagem", dica_cuidado: "Sombra total. Se as folhas baixarem, regue imediatamente." },
  { id_original: 8,   nome: "Lírio da Paz",               tamanho: "P15",           preco_padrao: 44.90,  categoria: "Folhagem", dica_cuidado: "Limpe as folhas com pano úmido para respirar melhor." },
  { id_original: 9,   nome: "Lírio Laranja",              tamanho: "P15",           preco_padrao: 84.90,  categoria: "Vaso",     dica_cuidado: "Solo levemente úmido, evite pratinho com água." },
  { id_original: 10,  nome: "Lírio Rosa",                 tamanho: "P15",           preco_padrao: 97.90,  categoria: "Vaso",     dica_cuidado: "Luz difusa, sol forte queima as flores." },
  { id_original: 11,  nome: "Mini Rosa",                  tamanho: "P11",           preco_padrao: 39.90,  categoria: "Vaso",     dica_cuidado: "Precisa de sol direto por pelo menos 4h diárias." },
  { id_original: 12,  nome: "Mini Rosa",                  tamanho: "P15",           preco_padrao: 57.90,  categoria: "Vaso",     dica_cuidado: "Pode e retire as flores secas para estimular novas." },
  { id_original: 13,  nome: "Prímula",                    tamanho: "P11",           preco_padrao: 25.90,  categoria: "Flor",     dica_cuidado: "Gosta de clima frio e solo úmido." },
  // --- ORQUÍDEAS ---
  { id_original: 14,  nome: "Orquídea Cymbidium",         tamanho: "1 Haste",       preco_padrao: 179.90, categoria: "Orquídea", dica_cuidado: "Gosta de frio à noite para florescer." },
  { id_original: 15,  nome: "Orquídea Dendrobium",        tamanho: "P15",           preco_padrao: 119.90, categoria: "Orquídea", dica_cuidado: "Regue pouco no inverno (repouso)." },
  { id_original: 16,  nome: "Orquídea Denfal",            tamanho: "2 Hastes",      preco_padrao: 99.90,  categoria: "Orquídea", dica_cuidado: "Luz intensa é essencial para nova floração." },
  { id_original: 17,  nome: "Orquídea Phalaenopsis",      tamanho: "1 Haste P12",   preco_padrao: 189.00, categoria: "Orquídea", dica_cuidado: "Hidrate as raízes quando ficarem prateadas." },
  { id_original: 18,  nome: "Orquídea Phalaenopsis",      tamanho: "2 Hastes P09",  preco_padrao: 119.90, categoria: "Orquídea", dica_cuidado: "Ideal para interiores, luz indireta." },
  { id_original: 19,  nome: "Orquídea Phalaenopsis",      tamanho: "3 Hastes P09",  preco_padrao: 189.90, categoria: "Orquídea", dica_cuidado: "Use adubo de floração a cada 15 dias." },
  { id_original: 20,  nome: "Orq. Phalaenopsis Cascata",  tamanho: "1 Haste P15",   preco_padrao: 199.90, categoria: "Orquídea", dica_cuidado: "Não mude o vaso de lugar/posição frequentemente." },
  { id_original: 21,  nome: "Orq. Phalaenopsis Cascata",  tamanho: "2 Hastes P15",  preco_padrao: 199.90, categoria: "Orquídea", dica_cuidado: "Sustente a haste com tutor para não quebrar." },
  { id_original: 22,  nome: "Orq. Phalaenopsis Cascata",  tamanho: "3 Hastes P15",  preco_padrao: 199.90, categoria: "Orquídea", dica_cuidado: "Evite molhar as flores, mancha fácil." },
  // --- VASOS ENFEITADOS ---
  { id_original: 23,  nome: "Amarílis",                   tamanho: "P15",           preco_padrao: 57.90,  categoria: "Vaso",     dica_cuidado: "Após a flor secar, corte a haste mas mantenha as folhas." },
  { id_original: 24,  nome: "Antúrio",                    tamanho: "P11",           preco_padrao: 34.90,  categoria: "Vaso",     dica_cuidado: "Mantenha em local bem iluminado sem sol direto." },
  { id_original: 25,  nome: "Antúrio",                    tamanho: "P15",           preco_padrao: 65.90,  categoria: "Vaso",     dica_cuidado: "Borrife água nas folhas em dias secos." },
  { id_original: 26,  nome: "Antúrio",                    tamanho: "P17",           preco_padrao: 79.80,  categoria: "Vaso",     dica_cuidado: "Limpe as folhas com pano úmido frequentemente." },
  { id_original: 27,  nome: "Árvore da Felicidade",       tamanho: "P11",           preco_padrao: 26.90,  categoria: "Folhagem", dica_cuidado: "Odeia vento e ar condicionado direto." },
  { id_original: 28,  nome: "Azaleia",                    tamanho: "P11",           preco_padrao: 35.90,  categoria: "Vaso",     dica_cuidado: "Solo ácido e sempre úmido. Gosta de sol." },
  { id_original: 29,  nome: "Azaleia",                    tamanho: "P15",           preco_padrao: 57.90,  categoria: "Vaso",     dica_cuidado: "Se murchar, mergulhe o vaso em balde d'água." },
  { id_original: 30,  nome: "Azaleia",                    tamanho: "P17",           preco_padrao: 94.90,  categoria: "Vaso",     dica_cuidado: "Pode após a floração para manter o formato." },
  { id_original: 31,  nome: "Azaleia",                    tamanho: "P24",           preco_padrao: 118.90, categoria: "Vaso",     dica_cuidado: "Ideal para varandas e jardins externos." },
  { id_original: 32,  nome: "Bambu da Sorte",             tamanho: "P09",           preco_padrao: 56.90,  categoria: "Vaso",     dica_cuidado: "Troque a água semanalmente se cultivar na água." },
  { id_original: 33,  nome: "Bambu da Sorte",             tamanho: "P15",           preco_padrao: 86.90,  categoria: "Vaso",     dica_cuidado: "Não deixe exposto ao sol direto." },
  { id_original: 34,  nome: "Begônia",                    tamanho: "P11",           preco_padrao: 59.90,  categoria: "Vaso",     dica_cuidado: "Caule gordinho: armazena água, cuidado com rega excessiva." },
  { id_original: 35,  nome: "Begônia",                    tamanho: "P15",           preco_padrao: 109.90, categoria: "Vaso",     dica_cuidado: "Sombra com muita luminosidade." },
  { id_original: 36,  nome: "Begônia Rex",                tamanho: "P15",           preco_padrao: 37.90,  categoria: "Folhagem", dica_cuidado: "Folhagem sensível, regue apenas no solo." },
  { id_original: 37,  nome: "Bico de Papagaio",           tamanho: "P11",           preco_padrao: 36.90,  categoria: "Vaso",     dica_cuidado: "Natalina: precisa de escuridão total à noite." },
  { id_original: 38,  nome: "Bico de Papagaio",           tamanho: "P15",           preco_padrao: 54.90,  categoria: "Vaso",     dica_cuidado: "Sensível a quebra de galhos, manuseie com cuidado." },
  { id_original: 39,  nome: "Bola Belga",                 tamanho: "Padrão",        preco_padrao: 96.90,  categoria: "Vaso",     dica_cuidado: "Mantenha formato arredondado com podas leves." },
  { id_original: 40,  nome: "Bromélia",                   tamanho: "P15",           preco_padrao: 74.90,  categoria: "Vaso",     dica_cuidado: "Mantenha água limpa no 'copinho' central da planta." },
  { id_original: 41,  nome: "Celósia",                    tamanho: "P15",           preco_padrao: 29.90,  categoria: "Vaso",     dica_cuidado: "Flor aveludada, não molhe a flor diretamente." },
  { id_original: 42,  nome: "Mini Suculenta",             tamanho: "P06",           preco_padrao: 24.90,  categoria: "Vaso",     dica_cuidado: "Sol direto. Rega mínima (gota a gota)." },
  { id_original: 43,  nome: "Bromélia Briviese",          tamanho: "P15",           preco_padrao: 46.90,  categoria: "Vaso",     dica_cuidado: "Luz filtrada, ideal para interiores." },
  { id_original: 44,  nome: "Calandiva",                  tamanho: "P06",           preco_padrao: 7.90,   categoria: "Vaso",     dica_cuidado: "Resistente, espere o solo secar totalmente." },
  { id_original: 45,  nome: "Calandiva",                  tamanho: "P09",           preco_padrao: 16.90,  categoria: "Vaso",     dica_cuidado: "Evite ambientes muito úmidos (banheiros)." },
  { id_original: 46,  nome: "Calandiva",                  tamanho: "P11",           preco_padrao: 24.90,  categoria: "Vaso",     dica_cuidado: "Floração duradoura se pegar um pouco de sol." },
  { id_original: 47,  nome: "Calandiva",                  tamanho: "P15",           preco_padrao: 51.90,  categoria: "Vaso",     dica_cuidado: "Fácil de cuidar, ótima para presentes." },
  { id_original: 48,  nome: "Callas",                     tamanho: "P15",           preco_padrao: 76.90,  categoria: "Vaso",     dica_cuidado: "Solo úmido constantemente, gosta de água." },
  { id_original: 49,  nome: "Ciclamen",                   tamanho: "P11",           preco_padrao: 24.90,  categoria: "Flor",     dica_cuidado: "Gosta de gelo/água gelada na rega. Clima frio." },
  { id_original: 50,  nome: "Ciclamen",                   tamanho: "P15",           preco_padrao: 59.90,  categoria: "Flor",     dica_cuidado: "Dorme no verão (perde folhas) e brota no inverno." },
  { id_original: 51,  nome: "Crisântemo",                 tamanho: "P11",           preco_padrao: 24.90,  categoria: "Vaso",     dica_cuidado: "Luz solar direta pela manhã ajuda a manter botões." },
  { id_original: 52,  nome: "Crisântemo",                 tamanho: "P15",           preco_padrao: 44.90,  categoria: "Vaso",     dica_cuidado: "Evite molhar as flores para não fungar." },
  { id_original: 53,  nome: "Flor de Maio",               tamanho: "P11",           preco_padrao: 21.90,  categoria: "Vaso",     dica_cuidado: "Cacto de floresta: gosta de meia sombra, não sol pleno." },
  { id_original: 54,  nome: "Ficus Lirata",               tamanho: "P15",           preco_padrao: 47.90,  categoria: "Árvore",   dica_cuidado: "Limpe as folhas grandes para fotossíntese." },
  { id_original: 55,  nome: "Ficus Lirata",               tamanho: "P17",           preco_padrao: 179.90, categoria: "Árvore",   dica_cuidado: "Gire o vaso mensalmente para não entortar." },
  { id_original: 56,  nome: "Gérbera",                    tamanho: "P12",           preco_padrao: 44.90,  categoria: "Vaso",     dica_cuidado: "Ventilação é crucial para evitar oídio (pó branco)." },
  { id_original: 57,  nome: "Gérbera",                    tamanho: "P15",           preco_padrao: 53.90,  categoria: "Vaso",     dica_cuidado: "Solo drenado, não deixe água acumulada." },
  // --- CORTE ---
  { id_original: 101, nome: "Anastácia",                  tamanho: "Maço",          preco_padrao: 15.90,  categoria: "Corte",    dica_cuidado: "Corte 2cm da base na diagonal a cada 2 dias." },
  { id_original: 102, nome: "Antúrio Corte",              tamanho: "Unidade",       preco_padrao: 15.90,  categoria: "Corte",    dica_cuidado: "Corte o talo embaixo d'água evitar bolhas." },
  { id_original: 103, nome: "Aricana",                    tamanho: "Maço",          preco_padrao: 5.90,   categoria: "Corte",    dica_cuidado: "Borrife água nas folhas em dias quentes." },
  { id_original: 104, nome: "Aspargo",                    tamanho: "Maço",          preco_padrao: 2.90,   categoria: "Corte",    dica_cuidado: "Mantenha longe do sol direto." },
  { id_original: 105, nome: "Aster",                      tamanho: "Maço",          preco_padrao: 5.90,   categoria: "Corte",    dica_cuidado: "Retire folhas que ficariam submersas." },
  { id_original: 106, nome: "Astromélia",                 tamanho: "10 un",         preco_padrao: 8.90,   categoria: "Corte",    dica_cuidado: "Arranque os pistilos de dentro da flor." },
  { id_original: 107, nome: "Avenca",                     tamanho: "Maço",          preco_padrao: 2.90,   categoria: "Corte",    dica_cuidado: "Borrife água nela todo dia." },
  { id_original: 108, nome: "Boca de Leão",               tamanho: "Maço",          preco_padrao: 11.90,  categoria: "Corte",    dica_cuidado: "Mantenha a água gelada." },
  { id_original: 109, nome: "Cáspia",                     tamanho: "Maço",          preco_padrao: 12.90,  categoria: "Corte",    dica_cuidado: "Pode secar para arranjo permanente." },
  { id_original: 110, nome: "Celósia Corte",              tamanho: "08 un",         preco_padrao: 10.90,  categoria: "Corte",    dica_cuidado: "Nunca molhe a parte aveludada." },
  { id_original: 111, nome: "Copo de Leite",              tamanho: "12 un",         preco_padrao: 10.90,  categoria: "Corte",    dica_cuidado: "Apenas 3 dedos de água no vaso." },
  { id_original: 112, nome: "Cravínea",                   tamanho: "12 un",         preco_padrao: 4.90,   categoria: "Corte",    dica_cuidado: "Corte o talo entre os 'nós'." },
  { id_original: 113, nome: "Cravo",                      tamanho: "Maço",          preco_padrao: 23.90,  categoria: "Corte",    dica_cuidado: "2 gotas de água sanitária na água." },
  { id_original: 114, nome: "Crisântemo Corte",           tamanho: "Maço",          preco_padrao: 6.90,   categoria: "Corte",    dica_cuidado: "Lave bem o vaso com sabão." },
  { id_original: 115, nome: "Erígio",                     tamanho: "Maço",          preco_padrao: 24.90,  categoria: "Corte",    dica_cuidado: "Dura semanas, vira decoração rústica." },
  { id_original: 116, nome: "Estatice",                   tamanho: "Maço",          preco_padrao: 11.90,  categoria: "Corte",    dica_cuidado: "Pendure de cabeça para baixo para secar." },
  { id_original: 117, nome: "Eucaflor",                   tamanho: "Maço",          preco_padrao: 7.90,   categoria: "Corte",    dica_cuidado: "Amasse a ponta do caule para hidratar." },
  { id_original: 118, nome: "Flor de Cenoura",            tamanho: "10 un",         preco_padrao: 8.90,   categoria: "Corte",    dica_cuidado: "Use água filtrada se possível." },
  { id_original: 119, nome: "Flor de Lótus",              tamanho: "Maço",          preco_padrao: 10.90,  categoria: "Corte",    dica_cuidado: "Troque a água 2x ao dia." },
  { id_original: 120, nome: "Gérbera Corte",              tamanho: "12 un",         preco_padrao: 9.90,   categoria: "Corte",    dica_cuidado: "Pouquíssima água (3cm) no vaso." },
  { id_original: 121, nome: "Gipson",                     tamanho: "Maço",          preco_padrao: 11.90,  categoria: "Corte",    dica_cuidado: "Não molhe as flores brancas." },
  { id_original: 122, nome: "Girassol Corte",             tamanho: "06 un",         preco_padrao: 18.90,  categoria: "Corte",    dica_cuidado: "Complete o vaso diariamente." },
  { id_original: 123, nome: "Goivo",                      tamanho: "10 un",         preco_padrao: 14.90,  categoria: "Corte",    dica_cuidado: "Retire flores murchas de baixo." },
  { id_original: 124, nome: "Hortênsia Corte",            tamanho: "Maço",          preco_padrao: 7.90,   categoria: "Corte",    dica_cuidado: "Mergulhe a cabeça na água gelada se murchar." },
  { id_original: 125, nome: "Junco",                      tamanho: "Maço",          preco_padrao: 1.50,   categoria: "Corte",    dica_cuidado: "Mantenha a base sempre limpa." },
  { id_original: 126, nome: "Kalandiva Corte",            tamanho: "Maço",          preco_padrao: 6.90,   categoria: "Corte",    dica_cuidado: "Resistente fora d'água por horas." },
  { id_original: 127, nome: "Lírio Corte",                tamanho: "05 un",         preco_padrao: 39.90,  categoria: "Corte",    dica_cuidado: "Retire o pólen (pó laranja) com a mão." },
  { id_original: 128, nome: "Lisiantus",                  tamanho: "Maço",          preco_padrao: 26.90,  categoria: "Corte",    dica_cuidado: "Longe de fruteiras (etileno)." },
  { id_original: 129, nome: "Mini Rosa Spray",            tamanho: "Maço",          preco_padrao: 16.90,  categoria: "Corte",    dica_cuidado: "Retire espinhos da parte submersa." },
  { id_original: 130, nome: "Murta",                      tamanho: "Maço",          preco_padrao: 2.90,   categoria: "Corte",    dica_cuidado: "Lave os caules antes de por no vaso." },
  { id_original: 131, nome: "Pitosporo",                  tamanho: "Maço",          preco_padrao: 6.90,   categoria: "Corte",    dica_cuidado: "Apenas complete a água." },
  { id_original: 132, nome: "Rabo de Gato",               tamanho: "15 un",         preco_padrao: 5.90,   categoria: "Corte",    dica_cuidado: "Evite manusear muito a espiga." },
  { id_original: 133, nome: "Rainha Margarida",           tamanho: "10 un",         preco_padrao: 17.90,  categoria: "Corte",    dica_cuidado: "Água com açúcar ajuda na cor." },
  { id_original: 134, nome: "Rosa Inglesa",               tamanho: "08 un",         preco_padrao: 46.90,  categoria: "Corte",    dica_cuidado: "Retire as pétalas externas 'de guarda'." },
  { id_original: 135, nome: "Ruscus",                     tamanho: "Maço",          preco_padrao: 10.90,  categoria: "Corte",    dica_cuidado: "Troque a água só quando turva." },
  { id_original: 136, nome: "Tango",                      tamanho: "Maço",          preco_padrao: 5.90,   categoria: "Corte",    dica_cuidado: "Sacuda para cair pólen velho." },
  { id_original: 137, nome: "Tulipa Corte",               tamanho: "10 un",         preco_padrao: 32.90,  categoria: "Corte",    dica_cuidado: "Use pedras de gelo na água." },
  // --- EXTRAS ---
  { id_original: 200, nome: "Tulipa Vaso",                tamanho: "P15",           preco_padrao: 84.90,  categoria: "Vaso",     dica_cuidado: "Gelo sobre a terra todo dia. Ambiente frio." },
  { id_original: 201, nome: "Violeta",                    tamanho: "P11",           preco_padrao: 19.90,  categoria: "Flor",     dica_cuidado: "Regue pelo pratinho, nunca por cima." },
  { id_original: 202, nome: "Zamiocuca",                  tamanho: "P11",           preco_padrao: 34.90,  categoria: "Folhagem", dica_cuidado: "Regue muito pouco, 1x ao mês." },
  { id_original: 203, nome: "Zamiocuca",                  tamanho: "P15",           preco_padrao: 86.90,  categoria: "Folhagem", dica_cuidado: "Super resistente a ar condicionado." },
  { id_original: 204, nome: "Zamiocuca",                  tamanho: "P17",           preco_padrao: 108.90, categoria: "Folhagem", dica_cuidado: "Ideal para cantos escuros." },
  { id_original: 205, nome: "Zamiocuca Black",            tamanho: "P15",           preco_padrao: 96.90,  categoria: "Folhagem", dica_cuidado: "Cor escura precisa de um pouco mais de luz que a verde." },
  { id_original: 206, nome: "Zamiocuca Black",            tamanho: "P17",           preco_padrao: 116.90, categoria: "Folhagem", dica_cuidado: "Crescimento lento, paciência." },
]
